### ISSUE TITLE
Fixing overflowing pixels on add-habit-page

### ISSUE THREAD

**Issue by HelenaKeller** [92Andy/flutter_beautiful_UIs#12]
The add-habit-page has overflowing pixels at the bottom when simulated with iPhone SE 3. Generation.

![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-08-25 at 19 34 09](https://user-images.githubusercontent.com/20512988/186737031-19317b37-1466-4068-aaca-01e6f2e689f3.png)

**Comment by 92Andy** [comment]
Either cannot be readjusted or this bug has already been solved
